### ISSUE TITLE
Did not work anymore in Windows 10.

### ISSUE THREAD

**Issue by Alamo04** [dabear/FloatingGlucose#20]
Using that tool a long time now, but unfortunatly it stops working a few day ago.

Did not receive data from nightscout anymore.

Settings controlled, deleted and new entered didn't help.

![Sample](https://user-images.githubusercontent.com/36486505/194717988-ffc4fb90-ff88-4335-aebe-21d9dd7d6ae8.PNG)

**Comment by infossk** [comment]
I have the same problem.

**Comment by dabear** [comment]
any debug info? did you guys update nightscout recently? It is more likely to be a problem with newer nightscout releases than with windows 10. This project is btw not very active anymore

**Comment by Alamo04** [comment]
Sorry, didn't have debug info and the tool is deinstalled.
NS is always on the last Version.

I saw that the project isn't active anymore, but want to inform about this issue.

**Comment by infossk** [comment]
NS version: 14.2.6

glucose_log:

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FloatingGlucose.Classes.DataSources.Plugins.NightscoutPebbleEndpoint.<GetDataSourceDataAsync>d__55.MoveNext() in E:\Kode\prosjekter\FloatingGlucose\FloatingGlucose\Classes\DataSources\Plugins\NightscoutPebbleEndpoint\NightscoutPebbleEndpoint.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at FloatingGlucose.FloatingGlucose.<LoadGlucoseValue>d__18.MoveNext() in E:\Kode\prosjekter\FloatingGlucose\FloatingGlucose\FloatingGlucose.cs:line 236

**Comment by Alamo04** [comment]
Here another Log, same results.
[glucose_log.txt](https://github.com/dabear/FloatingGlucose/files/9944708/glucose_log.txt)

**Comment by GooGit** [comment]
It looks like the Pebble endpoint isn't available anymore.
/pebble does not work on my 14.2.6 Nightscout. But it is still there on my old site which is version 14.2.2

Edit:
Well, it looks like I was wrong. I updated my old Nightscout site on Heroku to 14.2.6 and the /pebble endpoint is there and works fine with FloatingGlucose. But it does not work with my new Nightscout which is hosted by ns.10be.de.

I'm going to contact their support and see what they say.

**Comment by GooGit** [comment]
My issue is resolved now.

I changed Nighscout version to DEV 15.0.0.0 on my hosted Nightscout and now both the /Pebble endpoint and FloatingGlucose works again.

**Comment by Alamo04** [comment]
Confirmed - with Dev 15.0.0.0 everything works again. :)

**Comment by whooze** [comment]
Just to be clear, it's working on 14.2.6 for me
